### Ref Code

In [1]:
import tiktoken
import torch

In [ ]:
import os

path = r'C:\ptoh\DeepLLM\data\input.txt'
if os.path.exists(path):
    with open(path, 'r', encoding='utf-8') as f:
        text = f.read()
else:
    text = ''
    print(f"No file found at {path}. Using empty fallback text.")

<>:3: SyntaxWarning: invalid escape sequence '\p'
<>:3: SyntaxWarning: invalid escape sequence '\p'
C:\Users\Abhishek Raj\AppData\Local\Temp\ipykernel_13788\3289695073.py:3: SyntaxWarning: invalid escape sequence '\p'
  path = 'C:\ptoh\DeepLLM\data\input.txt'


In [3]:
print(f"length of dataset in characters : {len(text)}")
print(text[:100])

length of dataset in characters : 1115394
First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You


In [4]:
chars = sorted(list(set(text)))
vocab_size = len(chars)
print("".join(chars))
print(vocab_size)


 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
65


In [5]:
# creating mappings from chars to integers
stoi  = {ch:i for i , ch in enumerate(chars)}
itos = {i:ch for i , ch in enumerate(chars)}
encode = lambda s: [stoi[c] for c in s]   #takes a string outputs a list of integers 
decode = lambda l: "".join(itos[i] for i in l) #takes a list of integers and outputs a string

print(encode("hi there"))
print(decode([46, 47, 1, 58, 46, 43, 56, 43]))

[46, 47, 1, 58, 46, 43, 56, 43]
hi there


In [6]:
data = torch.tensor(encode(text) , dtype = torch.long)
print(data.shape,data.dtype)
print(data[:10])

torch.Size([1115394]) torch.int64
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47])


In [7]:
n = int(0.9*len(data))
train_data = data[:n]
val_data = data[n:]

In [8]:
# the maximum length of chucks fed into the transformer is the block_size or context length
block_size = 8
train_data[:block_size+1]


tensor([18, 47, 56, 57, 58,  1, 15, 47, 58])

in the context of 18 47 comes next in the context of 18,47 56 comes next

In [9]:
x = train_data[:block_size]
y= train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input : {context} the target : {target}")

when input : tensor([18]) the target : 47
when input : tensor([18, 47]) the target : 56
when input : tensor([18, 47, 56]) the target : 57
when input : tensor([18, 47, 56, 57]) the target : 58
when input : tensor([18, 47, 56, 57, 58]) the target : 1
when input : tensor([18, 47, 56, 57, 58,  1]) the target : 15
when input : tensor([18, 47, 56, 57, 58,  1, 15]) the target : 47
when input : tensor([18, 47, 56, 57, 58,  1, 15, 47]) the target : 58


Now we introduce a batch dimension

In [10]:
torch.manual_seed(1337)
batch_size = 4  #how many independent sequence we process in parallel in forward backward pass
block_size = 8  #maximum context length for prediction.

def get_batch(split):
    # generate a small batches of data of input x and target y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data)-block_size , (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i + 1 : i + block_size +1] for i in ix])
    return x , y 

xb , yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)
print('--'*5)

for b in range(batch_size):       #batch dimension 
    for t in range(block_size):   #time dimension
        context = xb[b,:t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target :{target}")

inputs:
torch.Size([4, 8])
tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])
targets:
torch.Size([4, 8])
tensor([[43, 58,  5, 57,  1, 46, 43, 39],
        [53, 56,  1, 58, 46, 39, 58,  1],
        [58,  1, 58, 46, 39, 58,  1, 46],
        [17, 27, 10,  0, 21,  1, 54, 39]])
----------
when input is [24] the target :43
when input is [24, 43] the target :58
when input is [24, 43, 58] the target :5
when input is [24, 43, 58, 5] the target :57
when input is [24, 43, 58, 5, 57] the target :1
when input is [24, 43, 58, 5, 57, 1] the target :46
when input is [24, 43, 58, 5, 57, 1, 46] the target :43
when input is [24, 43, 58, 5, 57, 1, 46, 43] the target :39
when input is [44] the target :53
when input is [44, 53] the target :56
when input is [44, 53, 56] the target :1
when input is [44, 53, 56, 1] the target :58
when input is [44, 53, 56, 1, 58] the target :46
when input is [

### Working on the simplest Model Bi-Gram model

In [ ]:
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)


class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        #each token directly reads off the logits for the next token from the lookup table
        self.token_embedding_table = nn.Embedding(vocab_size,vocab_size)

    def forward(self,idx,targets=None):

        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx)  # (B,T,C)   C is the possible next characters
        # as cross_entropy takes in logits in format(B,C,T)
        
        if targets is None:
            loss = None
        else:    
            B ,T ,C = logits.shape
            logits = logits.view(B*T , C)  #flatten out B and T
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits ,targets) 
        return logits , loss 
    
    def generate(self,idx ,max_new_tokens):
        # idx is (B,T) array of indices in the current context 
        for _ in range(max_new_tokens):
            #get the predictions
            logits , loss = self(idx)  #this go to the forward() of self 
            logits = logits[:,-1,:] # becomes (B , C)
            # apply softmax to get probabilities
            probs = F.softmax(logits , dim=-1) # (B,C)
            # sample from the distribution
            idx_next = torch.multinomial(probs,num_samples=1)
            #append sampled index to the running sequence
            idx = torch.cat((idx,idx_next) , dim=1) # ( B ,T+1)
        return idx    

      

In [12]:
m = BigramLanguageModel(vocab_size)
logits,loss = m(xb , yb)
print(logits.shape)
print(loss)

torch.Size([32, 65])
tensor(4.8786, grad_fn=<NllLossBackward0>)


In [13]:
print(decode(m.generate(idx=torch.zeros((1,1),dtype = torch.long),max_new_tokens=100)[0].tolist()))


SKIcLT;AcELMoTbvZv C?nq-QE33:CJqkOKH-q;:la!oiywkHjgChzbQ?u!3bLIgwevmyFJGUGp
wnYWmnxKWWev-tDqXErVKLgJ


Creating the optimizer

In [14]:
optimizer = torch.optim.AdamW(m.parameters() ,lr = 1e-3)

In [15]:
batch_size = 32
for steps in range(100):
    
    xb , yb = get_batch('train')
    # sample a batch of data
    logits , loss = m(xb,yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

    print(loss.item())

4.692410945892334
4.664144515991211
4.765714645385742
4.70655632019043
4.5956573486328125
4.7101240158081055
4.713661193847656
4.686909198760986
4.700076103210449
4.7182841300964355
4.715603351593018
4.684308052062988
4.745601177215576
4.735717296600342
4.666238784790039
4.58615255355835
4.714625835418701
4.671982765197754
4.715047359466553
4.744891166687012
4.630162715911865
4.707578182220459
4.670665264129639
4.582583427429199
4.739546298980713
4.674807071685791
4.805595874786377
4.749917507171631
4.691989421844482
4.604404926300049
4.721841335296631
4.741591930389404
4.6099629402160645
4.662769794464111
4.730099678039551
4.738433361053467
4.688235282897949
4.639987945556641
4.736632823944092
4.709773540496826
4.736939430236816
4.69184684753418
4.719646453857422
4.752516746520996
4.570086479187012
4.643786907196045
4.699163913726807
4.806960105895996
4.572142601013184
4.717066287994385
4.509502410888672
4.603540897369385
4.6649675369262695
4.712099075317383
4.736576557159424
4.812878

In [16]:
print(decode(m.generate(idx = torch.zeros((1,1),dtype = torch.long), max_new_tokens=500)[0].tolist()))


oTo.JUZ!!zqe!
xBP qbs$Gy'AcOmrLwwt
p$x;Seh-onQbfM?OjKbn'NwUAW -Np3fkz$FVwAUEa-wzWC -wQo-R!v -Mj?,SPiTyZ;o-opr$mOiPJEYD-CfigkzD3p3?zvS;ADz;.y?o,ivCuC'zqHxcVT cHA
rT'Fd,SBMZyOslg!NXeF$sBe,juUzLq?w-wzP-h
ERjjxlgJzPbHxf$ q,q,KCDCU fqBOQT
SV&CW:xSVwZv'DG'NSPypDhKStKzC -$hslxIVzoivnp ,ethA:NCCGoi
tN!ljjP3fwJMwNelgUzzPGJlgihJ!d?q.d
pSPYgCuCJrIFtb
jQXg
pA.P LP,SPJi
DBcuBM:CixjJ$Jzkq,OLf3KLQLMGph$O 3DfiPHnXKuHMlyjxEiyZib3FaHV-oJa!zoc'XSP :CKGUhd?lgCOF$;;DTHZMlvvcmZAm;:iv'MMgO&Ywbc;BLCUd&vZINLIzkuTGZa
D.?


The mathematical trick in self-attention

In [18]:
# consider the following toy example:

torch.manual_seed(1337)
B,T,C = 4,8,2  #batch , time , channel 
x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [ ]:
# we want x[b,t] = mean_{i<=t} x[b,i]
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b,: t+1] #(t,c)
        xbow[b,t] = torch.mean(xprev,0) #averaging over the 0th dimension

tensor([[ 0.1808, -0.0700],
        [-0.0894, -0.4926],
        [ 0.1490, -0.3199],
        [ 0.3504, -0.2238],
        [ 0.3525,  0.0545],
        [ 0.0688, -0.0396],
        [ 0.0927, -0.0682],
        [-0.0341,  0.1332]])

tensor([[ 0.1808, -0.0700],
        [-0.3596, -0.9152],
        [ 0.6258,  0.0255],
        [ 0.9545,  0.0643],
        [ 0.3612,  1.1679],
        [-1.3499, -0.5102],
        [ 0.2360, -0.2398],
        [-0.9211,  1.5433]])